backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "youngmangame"
    label: "Young Man Game" 
    folder: "content/youngmangame"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "hidden", default: "Podcast"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "life"
    label: "Life Post" 
    folder: "content/life"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  
  
